apiVersion: v1
kind: Service
metadata:
  name: oss-todomvc-app
  labels:
    app: oss-todomvc-app
spec:
  ports:
  - port: 8080
    name: oss-todomvc-app
    nodePort: 30501
  selector:
    app: oss-todomvc-app
  type: NodePort
