apiVersion: v1
kind: Service
metadata:
  name: oss-todomvc-gateway
  labels:
    app: oss-todomvc-gateway
spec:
  ports:
  - port: 8090
    name: oss-todomvc-gateway
    nodePort: 30502
  selector:
    app: oss-todomvc-gateway
  type: NodePort
