apiVersion: v1
kind: Service
metadata:
  name: oss-todomvc-thymeleaf
  labels:
    app: oss-todomvc-thymeleaf
spec:
  ports:
  - port: 8083
    name: oss-todomvc-thymeleaf
    nodePort: 30503
  selector:
    app: oss-todomvc-thymeleaf
  type: NodePort
