apiVersion: v1
kind: Service
metadata:
  name: oss-eureka
  labels:
    app: oss-eureka
spec:
  ports:
  - port: 8761
    name: oss-eureka
    nodePort: 30001
  selector:
    app: oss-eureka
  type: NodePort
