apiVersion: v1
kind: Service
metadata:
  name: oss-admin
  labels:
    app: oss-admin
spec:
  ports:
    - port: 8700
      name: oss-admin-port
    - port: 5005
      name: java-debug
  selector:
    app: oss-admin
  type: NodePort
