# the template for deployment of k8s

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eureka-service-#{PEER_NAME}#
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      annotations:
        pod.beta.kubernetes.io/hostname: eureka.local
      labels:
        app-group: eureka-service
        app: eureka-#{PEER_NAME}#
        tag: home1-oss
    spec:
      containers:
      - image: home1oss/oss-eureka:latest
        imagePullPolicy: Always
        name: eureka-service
        ports:
        - containerPort: 8761
          name: web
          protocol: TCP
#        envFrom:
#        - configMapRef:
#            name: eureka-config-common
#        - configMapRef:
#            name: eureka-config-#{PEER_NAME}#
        env:
        - name: EUREKA_CLIENT_FETCHREGISTRY
          value: "true"
        - name: EUREKA_CLIENT_REGISTERWITHEUREKA
          value: "true"
        - name: ENV
          valueFrom:
            configMapKeyRef:
              name: eureka-config-common
              key: ENV
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom:
            configMapKeyRef:
              name: eureka-config-common
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        - name: EUREKA_INSTANCE_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: eureka-config-#{PEER_NAME}#
              key: EUREKA_INSTANCE_HOSTNAME
        - name: EUREKA_INSTANCE_IP_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: eureka-config-#{PEER_NAME}#
              key: SPRING_CLOUD_CLIENT_IP_ADDRESS
#        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
#          valueFrom:
#            configMapKeyRef:
#              name: eureka-config-#{PEER_NAME}#
#              key: EUREKA_INSTANCE_PREFER_IP_ADDRESS
        - name: EUREKA_INSTANCE_NONSECUREPORT
          valueFrom:
            configMapKeyRef:
              name: eureka-config-common
              key: EUREKA_INSTANCE_NONSECUREPORT
        - name: PEER
          valueFrom:
            configMapKeyRef:
              name: eureka-config-#{PEER_NAME}#
              key: PEER
        - name: SECURITY_BASIC_ENABLED
          valueFrom:
            configMapKeyRef:
              name: eureka-config-common
              key: SECURITY_BASIC_ENABLED
        - name: SECURITY_USER_NAME
          valueFrom:
            configMapKeyRef:
              name: eureka-config-common
              key: SECURITY_USER_NAME
        - name: SECURITY_USER_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: eureka-config-common
              key: SECURITY_USER_PASSWORD
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: eureka-config-common
              key: SERVER_PORT
        - name: SPRING_APPLICATION_NAME
          valueFrom:
            configMapKeyRef:
              name: eureka-config-common
              key: SPRING_APPLICATION_NAME
        - name: SPRING_CLOUD_CLIENT_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: eureka-config-#{PEER_NAME}#
              key: SPRING_CLOUD_CLIENT_HOSTNAME
        - name: SPRING_CLOUD_CLIENT_IP_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: eureka-config-#{PEER_NAME}#
              key: SPRING_CLOUD_CLIENT_IP_ADDRESS
        - name: SPRING_PROFILES_ACTIVE
          value: "$(ENV).env"
        volumeMounts:
        - name: epty
          mountPath: /tmp
      volumes:
      - name: epty
        emptyDir: {}
