apiVersion: v1
kind: Service
metadata:
  name: configserver
  labels:
    app: configserver
spec:
  ports:
    - port: 8888
      name: configserver
      nodePort: 30000
  selector:
    app: configserver
  type: NodePort
