apiVersion: v1
kind: Service
metadata:
  name: oss-configserver
  labels:
    app: oss-configserver
spec:
  ports:
  - port: 8888
    name: oss-configserver
    nodePort: 30000
  selector:
    app: oss-configserver
  type: NodePort
