apiVersion: v1
kind: Service
metadata:
  name: oss-eureka-cluster
  labels:
    app: oss-eureka-cluster
spec:
  ports:
  - port: 8761
    name: oss-eureka-cluster
    nodePort: 30100
  selector:
    app: oss-eureka-cluster
  #clusterIP: None
  #type: NodePort